name: testagram-supabase

services:
  storage:
    volumes:
      - ${TESTAGRAM_STORAGE_ROOT:-/var/lib/testagram/storage}/supabase:/var/lib/storage:z
    environment:
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage

  imgproxy:
    volumes:
      - ${TESTAGRAM_STORAGE_ROOT:-/var/lib/testagram/storage}/supabase:/var/lib/storage:z

networks:
  default:
    name: testagram-supabase
