name: testagram-supabase

services:
  api-gw:
    ports: !override
      - "127.0.0.1:8000:8000"
  storage:
    volumes:
      - ${TESTAGRAM_STORAGE_ROOT:-/var/lib/testagram/storage}/supabase:/var/lib/storage:z
    environment:
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage

  imgproxy:
    volumes:
      - ${TESTAGRAM_STORAGE_ROOT:-/var/lib/testagram/storage}/supabase:/var/lib/storage:z

networks:
  default:
    name: testagram-supabase
